[package]
name = "adventofcode2022-rs"
version = "0.1.0"
edition = "2021"

[day01]
crate-type = ["lib"]
bench = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
